### ISSUE TITLE
development roadmap

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/dht#1]
Here are some ideas for degauss helper tools functions that I've collected:

- [x] `greeting()` would welcome the user, state the name of the geomarker and version of degauss container, provide a brief descriptive of the geomarker and a link to more information for the specific geomarker, print link degauss.org (for troubleshooting), provide a link to the redcap survey?
- [x] `check_for_column()` would check for a given column name and optionally a column type; return a useful message if not available
- [x] `read_lat_lon_csv()` would take file path to input csv file and return both the deduplicated tibble (nested on lat/lon) and the raw data
- [x] `write_geomarker_file()` writes files after merging back with raw_data; geomarker name (and version of container? or date ran?)
- [x] date formatting functions piloted in `schwartz` container
- [x] a quick function to suppress all package startup messages?
- [x] a `usethis` like function for utilizing the degauss template repository
- [x] is there a way to log all container and R output into a log file so users could send that file rather than a screenshot when there are problems? (*this can be done in the shell application; not in this R package here*)
- [x] a working version of `mappp::mappp()` or equivalent so we can do progress bars for parallel processing (*parallel processing not used except for in `geocoder`; skip this for now*)

**Comment by cole-brokamp** [comment]
@erikarasnick once you add a brief description of the steps necessary to create a new container with `dht::use_degauss_container()` to the README, can you please deprecate the degauss_template repository (point it here instead), and close this issue?

**Comment by erikarasnick** [comment]
Yes, should I archive the repo for degauss_template?

**Comment by cole-brokamp** [comment]
yes, good call!
