### ISSUE TITLE
readme updates everywhere

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/dht#52]
Holding this issue here, but below actions need to completed for all degauss repos.  We should think about creating a function to auto create the badges based on env metadata to prevent doing this manually each time.

- [ ] updated badges to include version and gha build status as in https://github.com/degauss-org/fortunes/blob/main/README.md
- [ ] make description env metadata, description in readme, and github.com's description all identical
- [ ] add citation files?
- [ ] use updated degauss hex
- [ ] make sure output variable names are documented explicitly
- [ ] add CITATION.cff

**Comment by cole-brokamp** [comment]
following the [README template](https://github.com/degauss-org/dht/blob/master/inst/degauss_README.md) in {dht} should now adhere to all of these requirements above.

**Comment by cole-brokamp** [comment]
will track this in #57 as all code and readme updates are being done at the same time
